In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## loading data
YB = pd.read_csv('C:/Users/User/Desktop/용봉 일별 (2013~2022).csv', encoding='cp949')
NJ = pd.read_csv('C:/Users/User/Desktop/나주 일별 (2013~2022).csv', encoding='cp949')

In [2]:
YB

date   WT   pH     EC    DO  TOC     TN     TP  Chla  pct
0     2013-01-01  4.1  6.9  406.0  10.8  2.8    NaN    NaN   7.0  0.6
1     2013-01-02  4.3  6.9  431.0   9.2  2.8    NaN    NaN   7.1  0.5
2     2013-01-03  3.8  6.9  417.0   7.6  3.1    NaN    NaN   7.2  0.0
3     2013-01-04  3.3  6.9  402.0   8.8  2.7    NaN    NaN   7.1  NaN
4     2013-01-05  3.2  6.9  409.0   8.8  2.8    NaN    NaN   7.2  NaN
...          ...  ...  ...    ...   ...  ...    ...    ...   ...  ...
3647  2022-12-27  6.0  6.7  611.0   8.7  4.1  6.837  0.071  46.8  NaN
3648  2022-12-28  6.3  6.7  638.0   8.7  4.1  7.334  0.083  60.1  NaN
3649  2022-12-29  7.0  6.6  735.0   8.4  3.7  7.335  0.083  64.9  NaN
3650  2022-12-30  7.4  6.6  717.0   8.2  3.8  7.257  0.068  57.7  NaN
3651  2022-12-31  7.5  6.6  672.0   7.3  3.9  7.293  0.061  47.5  NaN

[3652 rows x 10 columns]

In [3]:
NJ

date   WT   pH     EC    DO   TB  TOC     TN     TP  Chla  pct
0     2013-01-01  3.1  6.8  278.0  12.2  1.7  2.0    NaN    NaN  10.7  0.6
1     2013-01-02  3.1  6.8  284.0  12.1  1.4  2.1    NaN    NaN  12.4  0.5
2     2013-01-03  2.7  6.7  289.0  11.7  1.3  2.2    NaN    NaN  13.3  0.0
3     2013-01-04  2.3  6.7  290.0    12  2.3  2.6    NaN    NaN  13.3  NaN
4     2013-01-05  2.6  6.7  291.0  11.9  1.3  2.5    NaN    NaN  13.2  NaN
...          ...  ...  ...    ...   ...  ...  ...    ...    ...   ...  ...
3647  2022-12-27  5.0  7.8  493.0  12.1  5.9  4.9  5.703  0.022  21.7  NaN
3648  2022-12-28  5.2  7.6  505.0  11.5  5.8  4.7  6.125  0.029  17.2  NaN
3649  2022-12-29  5.0  7.7  497.0    12  6.2  4.8  6.028  0.052  22.7  NaN
3650  2022-12-30  5.2  8.1  477.0  13.4  6.4  5.0  5.979  0.049  30.2  NaN
3651  2022-12-31  5.2  8.3  470.0  13.7  6.9  5.0  5.956  0.045  37.8  NaN

[3652 rows x 11 columns]

In [4]:
from statsmodels.tsa.stattools import grangercausalitytests

In [16]:
grangercausalitytests(YB.drop(labels='date', axis=1), maxlag=4)

ValueError: could not convert string to float: 'ND'

In [12]:
?grangercausalitytests

In [17]:
import statsmodels.api as sm
from statsmodels.tsa.stattools import grangercausalitytests
import numpy as np
data = sm.datasets.macrodata.load_pandas()
data = data.data[["realgdp", "realcons"]].pct_change().dropna()

In [19]:
grangercausalitytests(data, 4)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=28.7248 , p=0.0000  , df_denom=198, df_num=1
ssr based chi2 test:   chi2=29.1600 , p=0.0000  , df=1
likelihood ratio test: chi2=27.2295 , p=0.0000  , df=1
parameter F test:         F=28.7248 , p=0.0000  , df_denom=198, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=18.9880 , p=0.0000  , df_denom=195, df_num=2
ssr based chi2 test:   chi2=38.9498 , p=0.0000  , df=2
likelihood ratio test: chi2=35.5873 , p=0.0000  , df=2
parameter F test:         F=18.9880 , p=0.0000  , df_denom=195, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=13.5015 , p=0.0000  , df_denom=192, df_num=3
ssr based chi2 test:   chi2=41.9812 , p=0.0000  , df=3
likelihood ratio test: chi2=38.0914 , p=0.0000  , df=3
parameter F test:         F=13.5015 , p=0.0000  , df_denom=192, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=10.9646 , p=0.0000  

{1: ({'ssr_ftest': (28.72480341484925, 2.3081455830242645e-07, 198.0, 1),
   'ssr_chi2test': (29.160027709013633, 6.663994390982135e-08, 1),
   'lrtest': (27.229456246460586, 1.8068480152069365e-07, 1),
   'params_ftest': (28.72480341484923, 2.3081455830242944e-07, 198.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (18.98804608410747, 2.9209045472774998e-08, 195.0, 2),
   'ssr_chi2test': (38.949838121246096, 3.484577407030394e-09, 2),
   'lrtest': (35.587256203442394, 1.8720847364547857e-08, 2),
   'params_ftest': (18.988046084107452, 2.9209045472775375e-08, 195.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (13.501476217751769, 4.961196622274045e-08, 192.0, 3),
   'ssr_chi2test': (41.981152614571904, 4.049246048504214e-09, 3),
   'lrtest': (38.091366257052414, 2.7033433661640424e-08, 3),
   'params_ftest': (13.501476217751758, 4.961196622274114e-08, 192.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 